### ISSUE TITLE
How can I make it effective globally

### ISSUE THREAD

**Issue by ljtnine** [noobexon1/XposedFakeLocation#1]
Very good, the module is working. When I specify an app, it works correctly. How can I make it effective globally?

**Comment by noobexon1** [comment]
Glad to hear the module is working for you. 

The state of the global effect feature is currently unstable. I didn't have the time to optimize and test it properly and I wouldn't recommend using it unless you really have to. If you decide to use it anyway, here is how you do it:

1. In the same place where you specify an app, select "System Framework" and reboot your device for the changes to take effect.
2. If you want to remove the global settings, than again you would have to deselect  "System Framework" and reboot for the changes to take effect
3. Right now the hooks for the pre-app feature and the global feature are different from one another, so you can experiment by turning both on. 

Hope this helps.

**Comment by ljtnine** [comment]
thx
